spring:
  datasource:
    url: jdbc:postgresql://cloud.aiaracorp.com:5432/pup
    username: admin
    password: qwer1595@!
    flyway:
      url: jdbc:postgresql://cloud.aiaracorp.com:5432/pup
      username: admin
      password: qwer1595@!
  flyway:
    enabled: false
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true