spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pup
    username: admin
    password: qwer1595@!
    flyway:
      url: jdbc:postgresql://localhost:5432/pup
      username: admin
      password: qwer1595@!
  flyway:
    enabled: true
    baselineOnMigrate: true
    baselineVersion: 1
    locations: classpath:migration
    sqlMigrationSuffixes: sql
springdoc:
  swagger-ui:
    enabled: false