apiVersion: v1
kind: Service
metadata:
  labels:
    app: pup-backend
  name: pup-backend-service
spec:
  type: NodePort
  selector:
    app: pup-backend
  ports:
    - port: 8099
      targetPort: 8080
